(function(){
 const S=RytmStats, Store=RytmStore, DAYS=['Mån','Tis','Ons','Tor','Fre','Lör','Sön'], MONTHS=['januari','februari','mars','april','maj','juni','juli','augusti','september','oktober','november','december'], COLORS=['#5da9e9','#77c7d9','#8e83d8','#ef9f76','#7dbf91','#d982a6'];
 let data=Store.load(), view=(location.hash.slice(1)||'today'), cursor=new Date(), selectedColor=COLORS[0], pendingDelete=null, installPrompt=null;
 const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])), fmt=d=>new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short'}).format(d), today=()=>S.iso(new Date());
 const nav=[['today','Idag','☀️'],['dashboard','Översikt','📊'],['week','Vecka','🗓️'],['month','Månad','📅'],['habits','Vanor','🌱'],['tasks','Att göra','✨']];
 function persist(message){if(!Store.save(data))toast('Kunde inte spara. Kontrollera webbläsarens lagring.');else if(message)toast(message)}
 function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t.timer);t.timer=setTimeout(()=>t.classList.remove('show'),2400)}
 function setupNav(){document.querySelectorAll('.desktop-nav,.mobile-nav').forEach(el=>el.innerHTML=nav.map(([id,label,icon])=>`<a href="#${id}" data-view="${id}" class="${view===id?'active':''}"><i>${icon}</i><span>${label}</span></a>`).join(''))}
 function setHead(eyebrow,title,sub){$('#viewEyebrow').textContent=eyebrow;$('#viewTitle').innerHTML=title;$('#viewSubtitle').textContent=sub}
 function render(){view=location.hash.slice(1)||'today';setupNav();const map={today:renderToday,dashboard:renderDashboard,week:renderWeek,month:renderMonth,habits:renderHabits,tasks:renderTasks};(map[view]||renderToday)();bindCommon()}
 function active(){return data.habits.filter(h=>!h.archived)}
 function scheduled(d){return active().filter(h=>S.isScheduled(h,d))}
 function statusButtons(h,date){const e=S.entry(h,date);return `<div class="status-actions"><button class="status done ${e?.status==='done'?'selected':''}" data-status="done" data-id="${h.id}" data-date="${S.iso(date)}" title="Genomförd">✓</button><button class="status skip ${e?.status==='skipped'?'selected':''}" data-status="skipped" data-id="${h.id}" data-date="${S.iso(date)}" title="Medvetet hoppad över">–</button></div>`}
 function habitCard(h,d){const e=S.entry(h,d),target=h.target?`${e?.value??0} / ${h.target.value} ${esc(h.target.unit)}`:'';return `<article class="today-item ${e?.status||''}" style="--habit:${h.color}"><div class="habit-symbol">${esc(h.icon)}</div><div class="item-copy"><span class="tag">${esc(h.category)}</span><h3>${esc(h.name)}</h3>${h.description?`<p>${esc(h.description)}</p>`:''}${target?`<button class="value-btn" data-value="${h.id}" data-date="${S.iso(d)}">${target}</button>`:''}</div>${statusButtons(h,d)}</article>`}
 function renderToday(){cursor=new Date();setHead('DIN DAG','En sak i taget.<br><span>Bygg din rytm.</span>','Dagens vanor och uppgifter, samlade på ett ställe.');const hs=scheduled(cursor),tasks=data.tasks.filter(t=>t.date===today());const done=hs.filter(h=>S.entry(h,cursor)?.status==='done').length,pct=hs.length?Math.round(done/hs.length*100):100;$('#app').innerHTML=`<section class="today-progress"><div><span>DAGENS FRAMSTEG</span><strong>${pct}%</strong><p>${done} av ${hs.length} vanor genomförda</p></div><div class="progress-ring" style="--progress:${pct}"><span>${pct}%</span></div></section><div class="content-grid"><section class="panel"><div class="section-head"><div><h2>Idag</h2><p>${new Intl.DateTimeFormat('sv-SE',{weekday:'long',day:'numeric',month:'long'}).format(cursor)}</p></div><button class="btn small primary" data-add-habit>＋ Vana</button></div><div class="today-list">${hs.length?hs.map(h=>habitCard(h,cursor)).join(''):empty('Inga vanor idag','Du är fri för dagen – eller lägg till en ny vana.')}</div></section><section class="panel task-panel"><div class="section-head"><div><h2>Att göra</h2><p>Engångsuppgifter för idag</p></div><button class="btn small secondary" data-add-task>＋ Uppgift</button></div>${taskList(tasks)}</section></div>`}
 function pctCard(label,value,meta,featured=''){return `<article class="metric ${featured}"><span>${label}</span><strong>${value}</strong><p>${meta}</p></article>`}
 function renderDashboard(){setHead('ÖVERSIKT','Se dina mönster.<br><span>Fira framstegen.</span>','En tydlig bild av hur din rytm utvecklas.');const hs=active(),now=new Date(),day=S.aggregate(hs,now,now),week=S.aggregate(hs,S.monday(now),now),month=S.aggregate(hs,new Date(now.getFullYear(),now.getMonth(),1,12),now),rank=hs.map(h=>({h,s:S.habit(h)})).sort((a,b)=>b.s.longest-a.s.longest),miss=[...rank].sort((a,b)=>a.s.rate-b.s.rate).slice(0,3);$('#app').innerHTML=`<section class="metrics">${pctCard('IDAG',day.percent+'%',`${day.done} genomförda`,'featured')}${pctCard('DENNA VECKA',week.percent+'%',`${week.skipped} överhoppade`)}${pctCard('DENNA MÅNAD',month.percent+'%',`${month.done} genomförda`)}${pctCard('AKTIVA VANOR',hs.length,'i din nuvarande rytm')}</section><div class="content-grid"><section class="panel"><div class="section-head"><div><h2>Bästa streaks</h2><p>Dina starkaste sviter</p></div></div>${rank.length?rank.slice(0,5).map(({h,s},i)=>`<div class="rank-row"><b>${i+1}</b><i style="background:${h.color}">${esc(h.icon)}</i><span>${esc(h.name)}</span><strong>${s.longest} dagar</strong></div>`).join(''):empty('Ingen statistik ännu','Markera en vana som klar för att börja.')}</section><section class="panel"><div class="section-head"><div><h2>Behöver mest stöd</h2><p>Vanor med lägst completion rate</p></div></div>${miss.length?miss.map(({h,s})=>`<div class="miss-row"><div><b>${esc(h.name)}</b><span>${s.rate}% totalt</span></div><div class="bar"><i style="width:${s.rate}%;background:${h.color}"></i></div></div>`).join(''):empty('Allt ser fint ut','Här visas mönster när du har mer data.')}</section></div><section class="panel graph-panel"><div class="section-head"><div><h2>Din rytm över tid</h2><p>De senaste 16 veckorna</p></div></div>${contributionGraph(hs)}</section>`}
 function weekDates(){const m=S.monday(cursor);return Array.from({length:7},(_,i)=>S.add(m,i))}
 function navHead(title,sub){return `<div class="section-head"><div><h2>${title}</h2><p>${sub}</p></div><div class="period-nav"><button data-prev>‹</button><button data-now>Idag</button><button data-next>›</button></div></div>`}
 function renderWeek(){setHead('VECKOVY','Veckans rytm.<br><span>Dag för dag.</span>','Genomförd, missad eller medvetet överhoppad.');const ds=weekDates(),hs=active();$('#app').innerHTML=`<section class="panel">${navHead('Veckans vanor',`${fmt(ds[0])} – ${fmt(ds[6])} ${ds[6].getFullYear()}`)}<div class="week-scroll"><div class="week-grid"><div></div>${ds.map(d=>`<div class="day-head ${S.iso(d)===today()?'today':''}">${DAYS[(d.getDay()+6)%7]}<b>${d.getDate()}</b></div>`).join('')}${hs.map(h=>`<button class="week-label" data-detail="${h.id}"><i style="background:${h.color}">${esc(h.icon)}</i><span>${esc(h.name)}</span></button>${ds.map(d=>weekCell(h,d)).join('')}`).join('')}</div></div><div class="legend"><span><i class="done"></i>Genomförd</span><span><i class="skipped"></i>Hoppad över</span><span><i class="missed"></i>Missad</span></div></section>`}
 function weekCell(h,d){const due=S.isScheduled(h,d),e=S.entry(h,d),future=d>new Date();let cls=e?.status||(!future&&due?'missed':'');return `<button class="week-cell ${cls} ${!due?'off':''}" ${due&&!future?`data-cycle="${h.id}" data-date="${S.iso(d)}"`:''} aria-label="${esc(h.name)} ${S.iso(d)}">${e?.status==='done'?'✓':e?.status==='skipped'?'–':!future&&due?'×':''}</button>`}
 function renderMonth(){setHead('MÅNAD','Se helheten.<br><span>En månad i taget.</span>','Välj en vana och se varje dag tydligt.');const hs=active(),selected=hs.find(h=>h.id===sessionStorage.getItem('monthHabit'))||hs[0],start=new Date(cursor.getFullYear(),cursor.getMonth(),1,12),end=new Date(cursor.getFullYear(),cursor.getMonth()+1,0,12),pad=(start.getDay()+6)%7,cells=[...Array(pad).fill(null),...S.range(start,end)];$('#app').innerHTML=`<section class="panel">${navHead('Månadsöversikt',`${MONTHS[cursor.getMonth()]} ${cursor.getFullYear()}`)}${hs.length?`<label class="habit-select">Vana <select id="monthHabit">${hs.map(h=>`<option value="${h.id}" ${h===selected?'selected':''}>${esc(h.name)}</option>`).join('')}</select></label><div class="month-days">${DAYS.map(d=>`<span>${d}</span>`).join('')}</div><div class="month-grid">${cells.map(d=>d?`<button class="month-day ${monthClass(selected,d)}" ${S.isScheduled(selected,d)&&d<=new Date()?`data-cycle="${selected.id}" data-date="${S.iso(d)}"`:''}><b>${d.getDate()}</b><i>${S.entry(selected,d)?.status==='done'?'✓':S.entry(selected,d)?.status==='skipped'?'–':''}</i></button>`:'<span></span>').join('')}</div>${habitStats(selected)}`:empty('Inga aktiva vanor','Skapa eller återaktivera en vana först.')}</section>`}
 function monthClass(h,d){const e=S.entry(h,d);return e?.status||(!S.isScheduled(h,d)?'off':d<new Date()?'missed':'')}
 function habitStats(h){const s=S.habit(h);return `<div class="habit-stats">${pctCard('NUVARANDE STREAK',s.current+' dagar','fortsätt så')}${pctCard('LÄNGSTA STREAK',s.longest+' dagar','personbästa')}${pctCard('TOTALT',s.total,'genomföranden')}${pctCard('COMPLETION RATE',s.rate+'%',`${s.week.percent}% denna vecka · ${s.month.percent}% denna månad`)}</div>`}
 function renderHabits(){setHead('DINA VANOR','Din samling.<br><span>Forma din vardag.</span>','Redigera, pausa och följ varje vana.');const act=active(),arch=data.habits.filter(h=>h.archived);$('#app').innerHTML=`<section class="panel"><div class="section-head"><div><h2>Aktiva vanor</h2><p>${act.length} vanor i din rytm</p></div><button class="btn small primary" data-add-habit>＋ Ny vana</button></div><div class="manage-list">${act.length?act.map(manageCard).join(''):empty('Inga aktiva vanor','Skapa en ny eller återaktivera en pausad vana.')}</div></section><section class="panel archived"><div class="section-head"><div><h2>Pausade vanor</h2><p>Historiken finns kvar</p></div></div><div class="manage-list">${arch.length?arch.map(manageCard).join(''):empty('Inga pausade vanor','Vanor du pausar visas här.')}</div></section>`}
 function scheduleText(h){const s=h.schedule;if(s.type==='daily')return'Varje dag';if(s.type==='timesPerWeek')return`${s.timesPerWeek} gånger per vecka`;return(s.weekdays||[]).map(n=>['Sön','Mån','Tis','Ons','Tor','Fre','Lör'][n]).join(', ')}
 function manageCard(h){const s=S.habit(h);return `<article class="manage-card"><i class="large-symbol" style="background:${h.color}">${esc(h.icon)}</i><div><span class="tag">${esc(h.category)}</span><h3>${esc(h.name)}</h3><p>${esc(h.description||scheduleText(h))}</p><small>${scheduleText(h)} · ${s.total} genomföranden · ${s.current} dagars streak</small></div><div class="manage-actions"><button class="icon-btn" data-edit="${h.id}" title="Redigera">✎</button><button class="icon-btn" data-archive="${h.id}" title="${h.archived?'Återaktivera':'Pausa'}">${h.archived?'↻':'Ⅱ'}</button><button class="icon-btn danger-text" data-delete="${h.id}" title="Ta bort">×</button></div></article>`}
 function renderTasks(){setHead('ATT GÖRA','Saker som blir klara.<br><span>Utan upprepning.</span>','En enkel lista för dina engångsuppgifter.');const open=data.tasks.filter(t=>!t.done).sort((a,b)=>a.date.localeCompare(b.date)),done=data.tasks.filter(t=>t.done);$('#app').innerHTML=`<section class="panel"><div class="section-head"><div><h2>Uppgifter</h2><p>${open.length} kvar att göra</p></div><button class="btn small primary" data-add-task>＋ Ny uppgift</button></div>${taskList(open)}${done.length?`<details class="done-tasks"><summary>Klart (${done.length})</summary>${taskList(done)}</details>`:''}</section>`}
 function taskList(tasks){return tasks.length?`<div class="task-list">${tasks.map(t=>`<article class="task ${t.done?'completed':''}"><button class="task-check" data-task-toggle="${t.id}">${t.done?'✓':''}</button><div><span class="tag">${esc(t.category||'Uppgift')}</span><h3>${esc(t.title)}</h3>${t.description?`<p>${esc(t.description)}</p>`:''}<small>${t.date===today()?'Idag':t.date}</small></div><div class="manage-actions"><button class="icon-btn" data-task-edit="${t.id}">✎</button><button class="icon-btn danger-text" data-task-delete="${t.id}">×</button></div></article>`).join('')}</div>`:empty('Inga uppgifter','Lägg till en sak du vill få ur vägen.')}
 function contributionGraph(hs){const start=S.add(new Date(),-111);return `<div class="contribution">${S.range(start,new Date()).map(d=>{const due=hs.filter(h=>S.isScheduled(h,d)),done=due.filter(h=>S.entry(h,d)?.status==='done').length,level=due.length?Math.ceil(done/due.length*4):0;return`<i class="level-${level}" title="${S.iso(d)}: ${done}/${due.length}"></i>`}).join('')}</div><div class="graph-key"><span>Mindre</span>${[0,1,2,3,4].map(n=>`<i class="level-${n}"></i>`).join('')}<span>Mer</span></div>`}
 function empty(title,text){return`<div class="empty"><b>✦</b><h3>${title}</h3><p>${text}</p></div>`}
 function bindCommon(){document.querySelectorAll('[data-add-habit]').forEach(b=>b.onclick=()=>openHabit());document.querySelectorAll('[data-add-task]').forEach(b=>b.onclick=()=>openTask());document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>setStatus(b.dataset.id,b.dataset.date,b.dataset.status));document.querySelectorAll('[data-cycle]').forEach(b=>b.onclick=()=>cycleStatus(b.dataset.cycle,b.dataset.date));document.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>setValue(b.dataset.value,b.dataset.date));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openHabit(b.dataset.edit));document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>archive(b.dataset.archive));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>confirmDelete('habit',b.dataset.delete));document.querySelectorAll('[data-task-toggle]').forEach(b=>b.onclick=()=>toggleTask(b.dataset.taskToggle));document.querySelectorAll('[data-task-edit]').forEach(b=>b.onclick=()=>openTask(b.dataset.taskEdit));document.querySelectorAll('[data-task-delete]').forEach(b=>b.onclick=()=>confirmDelete('task',b.dataset.taskDelete));document.querySelector('[data-prev]')?.addEventListener('click',()=>{cursor=view==='month'?new Date(cursor.getFullYear(),cursor.getMonth()-1,1):S.add(cursor,-7);render()});document.querySelector('[data-next]')?.addEventListener('click',()=>{cursor=view==='month'?new Date(cursor.getFullYear(),cursor.getMonth()+1,1):S.add(cursor,7);render()});document.querySelector('[data-now]')?.addEventListener('click',()=>{cursor=new Date();render()});$('#monthHabit')?.addEventListener('change',e=>{sessionStorage.setItem('monthHabit',e.target.value);render()})}
 function setStatus(id,date,status){const h=data.habits.find(x=>x.id===id),old=h.entries[date]?.status;if(old===status)delete h.entries[date];else h.entries[date]={status,value:h.entries[date]?.value??null};persist(old===status?'Status borttagen':status==='done'?'Snyggt – registrerat!':'Dagen är hoppad över');render()}
 function cycleStatus(id,date){const h=data.habits.find(x=>x.id===id),s=h.entries[date]?.status;if(!s)h.entries[date]={status:'done',value:null};else if(s==='done')h.entries[date]={status:'skipped',value:null};else delete h.entries[date];persist();render()}
 function setValue(id,date){const h=data.habits.find(x=>x.id===id),v=prompt(`Ange ${h.target.unit||'värde'} (mål: ${h.target.value})`,h.entries[date]?.value??'');if(v===null)return;const n=Number(v);if(!Number.isFinite(n)||n<0)return toast('Ange ett giltigt positivt tal.');h.entries[date]={status:n>=h.target.value?'done':h.entries[date]?.status||'pending',value:n};persist('Värdet är sparat');render()}
 function archive(id){const h=data.habits.find(x=>x.id===id);h.archived=!h.archived;persist(h.archived?'Vanan är pausad. Historiken finns kvar.':'Vanan är aktiv igen.');render()}
 function toggleTask(id){const t=data.tasks.find(x=>x.id===id);t.done=!t.done;persist(t.done?'Uppgiften är klar!':'Uppgiften öppnades igen');render()}
 function confirmDelete(type,id){pendingDelete={type,id};const item=type==='habit'?data.habits.find(x=>x.id===id):data.tasks.find(x=>x.id===id);$('#confirmText').textContent=type==='habit'?`Vanan ”${item.name}” och all dess historik försvinner permanent.`:`Uppgiften ”${item.title}” försvinner permanent.`;$('#confirmDialog').showModal()}
 function openHabit(id){const f=$('#habitForm'),h=data.habits.find(x=>x.id===id);f.reset();f.elements.id.value=h?.id||'';f.elements.name.value=h?.name||'';f.elements.description.value=h?.description||'';f.elements.category.value=h?.category||'';f.elements.startDate.value=h?.startDate||today();f.elements.icon.value=h?.icon||'✓';f.elements.scheduleType.value=h?.schedule?.type||'daily';f.elements.timesPerWeek.value=h?.schedule?.timesPerWeek||3;f.elements.targetValue.value=h?.target?.value||'';f.elements.targetUnit.value=h?.target?.unit||'';selectedColor=h?.color||COLORS[0];$('#habitDialogTitle').textContent=h?'Redigera vana':'Ny vana';renderColors();renderWeekdays(h?.schedule?.weekdays||[1,2,3,4,5]);scheduleFields();$('#habitDialog').showModal()}
 function renderColors(){$('#colorOptions').innerHTML=COLORS.map(c=>`<button type="button" class="color-choice ${c===selectedColor?'selected':''}" style="background:${c}" data-color="${c}"></button>`).join('');document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{selectedColor=b.dataset.color;renderColors()})}
 function renderWeekdays(selected){$('#weekdayOptions').innerHTML=DAYS.map((d,i)=>{const n=(i+1)%7;return`<label><input type="checkbox" value="${n}" ${selected.includes(n)?'checked':''}><span>${d}</span></label>`}).join('')}
 function scheduleFields(){const type=$('#scheduleType').value;$('#weekdaysWrap').hidden=type!=='weekdays';$('#timesWrap').hidden=type!=='timesPerWeek'}
 function openTask(id){const f=$('#taskForm'),t=data.tasks.find(x=>x.id===id);f.reset();f.elements.id.value=t?.id||'';f.elements.title.value=t?.title||'';f.elements.description.value=t?.description||'';f.elements.date.value=t?.date||today();f.elements.category.value=t?.category||'';$('#taskDialogTitle').textContent=t?'Redigera uppgift':'Ny uppgift';$('#taskDialog').showModal()}
 $('#habitForm').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),id=fd.get('id'),old=data.habits.find(h=>h.id===id),type=fd.get('scheduleType'),weekdays=[...$('#weekdayOptions').querySelectorAll(':checked')].map(x=>Number(x.value));if(type==='weekdays'&&!weekdays.length)return $('#habitError').textContent='Välj minst en veckodag.';const h={id:id||Store.uid(),name:fd.get('name').trim(),description:fd.get('description').trim(),category:fd.get('category').trim()||'Övrigt',color:selectedColor,icon:fd.get('icon'),startDate:fd.get('startDate'),schedule:{type,weekdays,timesPerWeek:Number(fd.get('timesPerWeek'))||3},target:fd.get('targetValue')?{value:Number(fd.get('targetValue')),unit:fd.get('targetUnit').trim()}:null,archived:old?.archived||false,createdAt:old?.createdAt||new Date().toISOString(),entries:old?.entries||{}};if(old)data.habits[data.habits.indexOf(old)]=h;else data.habits.push(h);persist(old?'Vanan är uppdaterad':'Vanan är tillagd');f.closest('dialog').close();render()};
 $('#taskForm').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),id=fd.get('id'),old=data.tasks.find(t=>t.id===id),t={id:id||Store.uid(),title:fd.get('title').trim(),description:fd.get('description').trim(),date:fd.get('date'),category:fd.get('category').trim(),done:old?.done||false,createdAt:old?.createdAt||new Date().toISOString()};if(old)data.tasks[data.tasks.indexOf(old)]=t;else data.tasks.push(t);persist(old?'Uppgiften är uppdaterad':'Uppgiften är tillagd');f.closest('dialog').close();render()};
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#scheduleType').onchange=scheduleFields;document.querySelectorAll('[data-confirm]').forEach(b=>b.onclick=()=>{if(b.dataset.confirm==='yes'&&pendingDelete){if(pendingDelete.type==='habit')data.habits=data.habits.filter(x=>x.id!==pendingDelete.id);else data.tasks=data.tasks.filter(x=>x.id!==pendingDelete.id);persist('Borttaget permanent');render()}pendingDelete=null;$('#confirmDialog').close()});window.addEventListener('hashchange',render);document.querySelectorAll('[data-go-today]').forEach(b=>b.onclick=()=>location.hash='today');$('#todayLabel').textContent=new Intl.DateTimeFormat('sv-SE',{weekday:'short',day:'numeric',month:'short'}).format(new Date());
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').hidden=true}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));render();
})();
