(function(){
 const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)}, date=s=>new Date(`${s}T12:00:00`), add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x}, monday=d=>add(d,-((d.getDay()+6)%7));
 const isScheduled=(h,d)=>{const k=iso(d);if(k<h.startDate||h.archived)return false;const s=h.schedule||{type:'daily'};if(s.type==='daily')return true;if(s.type==='weekdays')return (s.weekdays||[]).includes(d.getDay());return true};
 const entry=(h,d)=>h.entries?.[typeof d==='string'?d:iso(d)];
 function range(a,b){const out=[];for(let d=new Date(a);d<=b;d=add(d,1))out.push(new Date(d));return out}
 function rate(h,from,to){const days=range(from,to).filter(d=>isScheduled(h,d));let due=0,done=0,skipped=0;if(h.schedule?.type==='timesPerWeek'){const weeks={};days.forEach(d=>{const k=iso(monday(d));(weeks[k]||=[]).push(d)});Object.values(weeks).forEach(ds=>{const target=Math.min(h.schedule.timesPerWeek||1,ds.length),completed=ds.filter(d=>entry(h,d)?.status==='done').length,skip=Math.min(ds.filter(d=>entry(h,d)?.status==='skipped').length,target);done+=completed;skipped+=skip;due+=Math.max(0,target-skip)})}else days.forEach(d=>{const e=entry(h,d);if(e?.status==='skipped'){skipped++;return}due++;if(e?.status==='done')done++});return{done,due,skipped,percent:due?Math.min(100,Math.round(done/due*100)):0}}
 function streaks(h){const completed=Object.keys(h.entries||{}).filter(k=>h.entries[k].status==='done').sort();let longest=0,run=0,prev=null;completed.forEach(k=>{const d=date(k);if(prev&&Math.round((d-prev)/86400000)===1)run++;else run=1;longest=Math.max(longest,run);prev=d});let current=0,d=new Date();d.setHours(12,0,0,0);if(entry(h,d)?.status!=='done')d=add(d,-1);while(entry(h,d)?.status==='done'){current++;d=add(d,-1)}return{current,longest}}
 function habit(h,now=new Date()){const start=date(h.startDate),w=monday(now),m=new Date(now.getFullYear(),now.getMonth(),1,12),all=rate(h,start,now),week=rate(h,w,now),month=rate(h,m,now),st=streaks(h),total=Object.values(h.entries||{}).filter(e=>e.status==='done').length;return{...st,total,rate:all.percent,week,month}}
 function aggregate(habits,from,to){let due=0,done=0,skipped=0;habits.forEach(h=>{const x=rate(h,from,to);due+=x.due;done+=x.done;skipped+=x.skipped});return{done,due,skipped,percent:due?Math.round(done/due*100):0}}
 function weeklyWeightTrend(h,weeks=8,now=new Date()){const out=[];for(let i=weeks-1;i>=0;i--){const start=add(monday(now),-i*7),end=add(start,6),values=range(start,end).map(d=>entry(h,d)?.value).filter(Number.isFinite);if(values.length)out.push({start:iso(start),average:Math.round(values.reduce((a,b)=>a+b,0)/values.length*10)/10,count:values.length})}return out}
 function weeklyCount(h,d=new Date()){const start=monday(d),end=add(start,6),count=range(start,end).reduce((n,x)=>n+(entry(h,x)?.count||0),0),goal=h.tracking?.weeklyGoal||h.schedule?.timesPerWeek||1;return{count,goal,percent:Math.min(100,Math.round(count/goal*100)),start:iso(start)}}
 window.RytmStats={iso,date,add,monday,range,isScheduled,entry,rate,habit,aggregate,weeklyWeightTrend,weeklyCount};
})();
