const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
for(const file of ['storage.js','stats.js','app.js','sw.js'])new vm.Script(fs.readFileSync(path.join(root,file),'utf8'),{filename:file});
const memory=new Map();const context={window:{},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},crypto:{randomUUID:()=>`test-${memory.size}`},console,Date};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'storage.js'),'utf8'),context);vm.runInContext(fs.readFileSync(path.join(root,'stats.js'),'utf8'),context);
memory.set('rytm-habits-v1',JSON.stringify({habits:[{id:'old',name:'Gammal vana',color:'#123456',checks:{'2026-08-10':true}}]}));memory.delete('rytm-data-v2');const migrated=context.window.RytmStore.load();assert.equal(migrated.version,2);assert.equal(migrated.habits[0].entries['2026-08-10'].status,'done');assert(memory.has('rytm-habits-v1'),'Gamla datan ska lämnas orörd');assert(memory.has('rytm-data-v2'),'Migrerad kopia ska sparas');
const h={name:'Test',startDate:'2026-08-01',archived:false,schedule:{type:'daily'},entries:{'2026-08-10':{status:'done'},'2026-08-11':{status:'skipped'}}};const r=context.window.RytmStats.rate(h,new Date('2026-08-10T12:00:00'),new Date('2026-08-12T12:00:00'));assert.deepEqual(JSON.parse(JSON.stringify(r)),{done:1,due:2,skipped:1,percent:50});
const x={...h,schedule:{type:'timesPerWeek',timesPerWeek:3},entries:{'2026-08-10':{status:'done'},'2026-08-11':{status:'done'},'2026-08-12':{status:'done'}}};assert.equal(context.window.RytmStats.rate(x,new Date('2026-08-10T12:00:00'),new Date('2026-08-16T12:00:00')).percent,100);
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const ref of ['styles.css','storage.js','stats.js','app.js','manifest.webmanifest'])assert(html.includes(ref),`index.html saknar ${ref}`);for(const file of ['manifest.webmanifest','icons/icon.svg','.github/workflows/pages.yml'])assert(fs.existsSync(path.join(root,file)),`${file} saknas`);
console.log('OK: syntax, migration, statusstatistik, veckomål, filreferenser och PWA-filer.');
